// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '// Read more': https://github.com/vuejs/vue-next/pull/3399
    Blog: typeof import('./src/components/Blog.vue')['default']
    CommonList: typeof import('./src/components/CommonList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Myself: typeof import('./src/components/Myself.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}

export { }
