// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/pages/[...all].vue')['default']
    '// Read more': https://github.com/vuejs/vue-next/pull/3399
    App: typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/App.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Dddd: typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/components/Dddd.md')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LaRssSquare: typeof import('~icons/la/rss-square')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    MdiReplay: typeof import('~icons/mdi/replay')['default']
    Myself: typeof import('./src/components/Myself.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Pages: typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/pages/index.vue')['default']
    Posts: typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/pages/posts/index.md')['default']
    RiArticleLine: typeof import('~icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('~icons/ri/bookmark-line')['default']
    RiLightbulbLine: typeof import('~icons/ri/lightbulb-line')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiStickyNoteLine: typeof import('~icons/ri/sticky-note-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    RiZhihuFill: typeof import('~icons/ri/zhihu-fill')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    UilGithubAlt: typeof import('~icons/uil/github-alt')['default']
    Undefined: typeof import('./Users/zhangbaolong/Promise/test/vite_promise_blogs/promise_blogs/src/pages/index.vue')['default']
  }
}

export { }
